Context sharing is successful between rest and tcp
12th automation attempt

Locks are bypassed for some high level things! needs to be revisited
Partitioner logic is kinda done. Round robin only

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -32,6 +32,25 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-buildx-
 
+      - name: Load Docker image from cache
+        id: build-docker-image
+        if: steps.docker-cache.outputs.cache-hit != 'true'
+        run: |
+          echo "Cache not found, building Docker image"
+          docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --tag my-docker-image --file googom/.devcontainer/Dockerfile --load .
+
+      - name: Load Docker image from cache
+        id: load-docker-image
+        if: steps.docker-cache.outputs.cache-hit == 'true'
+        run:
+          echo "Cache hit, loading Docker image"
+          docker load -i /tmp/.buildx-cache/my-docker-image.tar || true
+
+      - name: Save Docker image to cache
+        if: steps.docker-cache.outputs.cache-hit != 'true'
+        run: |
+          docker save my-docker-image -o /tmp/.buildx-cache/my-docker-image.tar
+
       - name: Copy Dockerfile
         run: mkdir -p /tmp/docker && cp .devcontainer/Dockerfile /tmp/docker/Dockerfile
 
@@ -45,21 +64,20 @@ jobs:
             mkdir -p build &&
             cd build &&
             cmake .. &&
-            cmake --build . &&
-            cp Googom /workspace/build/Googom"
+            cmake --build ."
 
       - name: Create tarball of the built executable
         run: |
-          tar -czvf build/Googom.tar.gz -C build Googom
+          tar -czvf /workspace/build/Googom.tar.gz -C build Googom
 
       - name: Upload build artifacts
         uses: actions/upload-artifact@v2
         with:
           name: cmake-build-artifacts
-          path: build/Googom.tar.gz
+          path: /workspace/build/Googom.tar.gz
 
       - name: Publish package
         if: github.event_name == 'push'
         run: |
           gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}
-          gh release create v${{ github.run_number }} build/Googom.tar.gz --notes "Automated build"
+          gh release create v${{ github.run_number }} /workspace/build/Googom.tar.gz --notes "Automated build"
